version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew compileReleaseSources

  pushToKryptoWire:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Build Release
          command: ./gradlew aR
      - run:
          name: Push To Kryptowire
          command: curl -X POST "https://emm.kryptowire.com/api/submit" -F app=@./app/build/outputs/apk/release/app-release.apk -F key=$KRYPTOWIRE_API_KEY -F platform=android

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - pushToKryptoWire:
          filters:
            branches:
              only:
                - master

