version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Export Env Vars
          command: |
            export KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD
            export KEY_PASSWORD=$KEY_PASSWORD
            export KRYPTOWIRE_API_KEY=$KRYPTOWIRE_API_KEY
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew compileReleaseSources
      - run:
          name: Build release artifact
          command: |
            export KEYSTORE_PASSWORD=`cat /tmp/keystorepass.txt`
            export KEY_PASSWORD=`cat /tmp/keypass.txt`
            ./gradlew aR
      - run:
          name: Push to Krypowire for scanning
          command: |
            export  KRYPTOWIRE_API_KEY=`cat /tmp/apikey.txt`
            curl -X POST "https://emm.kryptowire.com/api/submit" -F app=@./app/build/outputs/apk/app-release.apk -F key=$KRYPTOWIRE_API_KEY -F platform=android
